services:
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
  chore-manager:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./resources/dev-data:/opt/chore-manager/resources
