name: Publish Docker image nightly
      
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      WAS_EDITED: ${{ steps.check_date.outputs.WAS_EDITED }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - id: check_date
        name: Check if there were commits in the last day
        if: ${{ github.event_name == 'schedule' }}
        run: echo '::set-output name=WAS_EDITED::'$(test -n "$(git log --format=%H --since='72 hours ago')" && echo 'true' || echo 'false')

  build:
    needs: [check_date]
    if: ${{ github.event_name == 'release' || needs.check_date.outputs.WAS_EDITED == 'true' }}
    runs-on: ubuntu-latest
    name: Build and push a Docker image
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx for Multi-Arch Build
        uses: docker/setup-buildx-action@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: laxsrbija/chore-manager
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "latest"
          platforms: linux/amd64,linux/arm64
