name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push a Docker image
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx for Multi-Arch Build
        uses: docker/setup-buildx-action@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: laxsrbija/chore-manager
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "latest"
          platforms: linux/amd64,linux/arm64
      - name: Publish readme to DockerHub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: laxsrbija/chore-manager
          readme: "./README.md"
