name: Publish Docker image nightly
      
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push a Docker image
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx for Multi-Arch Build
        uses: docker/setup-buildx-action@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: laxsrbija/chore-manager
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "latest"
          platforms: linux/amd64,linux/arm64
